// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

/*
4 * 4 矩阵为例

有16个结果，每个结果需要 8 个数 分 4次相乘
分开16个线程组，每组4个线程，每个线程执行一次相乘，把结果加上到当前组id的数据实行累加
16组线程执行完毕，返回16个结果，按顺序填入结果矩阵

*/


#define thread_x 4
#define thread_y 1
#define thread_z 1

#define thread_group_x thread_x * thread_x
#define thread_group_y 1
#define thread_group_z 1


struct Multip
{
    float a;
    float b;
};

RWStructuredBuffer<Multip> inputRawData;//64个数据
RWStructuredBuffer<int> outputBuffer;//16个结果


/*
* 目标是求 SV_GroupID  就知道当前执行的组id，通过判定x维度，就知道当前是第几组，就是第几个结果[1,1,1], [2,1,1] , [3,1,1]
* 
SV_DispatchThreadID = SV_GroupID  *  一个线程组的规格(numthreads)  +  SV_GroupThreadID
SV_GroupID = (SV_DispatchThreadID - SV_GroupThreadID) / 一个线程组的规格(numthreads)

//第二组的第二个线程执行时
SV_DispatchThreadID = ([1,0,0] * [4,1,1]) + (1,0,0) = (5,0,0)

*/


[numthreads(thread_x, thread_y, thread_z)]
void CSMain (uint3 groupThreadID : SV_GroupThreadID, uint3 id : SV_DispatchThreadID)
{
    uint3 _groupId = uint3((id.x - groupThreadID.x) / thread_x, (id.y - groupThreadID.y) / thread_y, (id.z - groupThreadID.z) / thread_z);
    //bool keepWaiting = true;
    //while (keepWaiting) {
        int originalValue;
        //InterlockedCompareExchange(outputBuffer[_groupId.x], 0, 1, originalValue);
        //if (originalValue == 0) {


            int idx = id.x + (id.y * thread_group_x * thread_x) + (id.z * thread_group_x * thread_x * thread_group_y * thread_y);
            float multipVal = inputRawData[idx].a * inputRawData[idx].b;

           // float resultAddCurGroup = outputBuffer[_groupId.x];
            //AllMemoryBarrierWithGroupSync();
            //outputBuffer[_groupId.x] = resultAddCurGroup + multipVal;

            InterlockedAdd(outputBuffer[_groupId.x], multipVal, originalValue);

            //InterlockedExchange(outputBuffer[_groupId.x], 0, originalValue);
    //        keepWaiting = false;
    //    }
    //}

}
